import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Input } from "@mui/material";
const inter = Inter({ subsets: ["latin"] });

export default function Login() {
  // Task 1: Create Login Screen
  //  https://pro.chakra-ui.com/components/application/authentication
  //  Use MUI Input elemnts https://mui.com/material-ui/react-table/

  return (
    <>
      <Head>
        <title>Log in page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="textLogin">
          <h2>Log in to your account</h2>
        </div>
        <div className="emailtextboxStyle">
          <Input
            className="email-input"
            color="primary"
            disabled={false}
            placeholder="Enter your Email Address "
            disableUnderline={true}
            style={{
              padding: " 8px 24px",
              border: "1px solid black",
              borderRadius: "10px",
            }}
          />
        </div>

        <div class></div>
      </main>
    </>
  );
}
