import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })
//  Task 1: Create Produts Tabel
//  https://react.pixelstrap.com/multikart-admin/products/physical/sub-category
//  https://mui.com/material-ui/react-table/ use MUI
//  Add button, https://mui.com/material-ui/react-dialog that opens a dialog upon onClikcEvent

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        <nav className='navbar'>
          <div className="logo">
            <span>Multikart</span>
          </div>

          <div className="searchbox">
            <input className="searchBar" type="text" placeholder="Search.." />
          </div>
        </nav>
        
        <div>
          <h3>Menu</h3>
          <ul className='sidebar-menu'>
            <li className='sidebarLi'> Dashboard </li>
            <li className='sidebarLi'> Products </li>
            <li className='sidebarLi'> Sales </li>
            <li className='sidebarLi'> Cupons </li>
            <li className='sidebarLi'> Pages </li>
            <li className='sidebarLi'> Media </li>
            <li className='sidebarLi'> Menus </li>
          </ul>
        </div>
      </main>
    </>
  )
}
